# Generated by Django 4.1.3 on 2022-12-04 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="Программист .Net",
                        max_length=255,
                        verbose_name="Название резюме",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=50, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=50, verbose_name="Фамилия"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="город Москва",
                        max_length=255,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="8 999 999 99 99",
                        max_length=25,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email_two",
                    models.EmailField(
                        blank=True,
                        default="example@mail.ru",
                        max_length=25,
                        verbose_name="Email",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="Кто Я?", verbose_name="О вас"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos/%Y/%m/%d/",
                        verbose_name="Аватар",
                    ),
                ),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
                ("is_pub", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={"verbose_name": "Резюме", "verbose_name_plural": "Резюме",},
        ),
    ]
